import { Template } from "./types";

export const TEMPLATES: Template[] = [
  {
    id: "hero-screenshot",
    name: "Hero Screenshot",
    description: "Full-screen screenshot with a bold headline on top",
    deviceTarget: "iphone-6.7",
    backgroundColor: "#1a1a2e",
    elements: [
      {
        type: "rectangle",
        x: 0,
        y: 0,
        width: 1290,
        height: 2796,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        name: "Background",
        fill: "#1a1a2e",
        stroke: "",
        strokeWidth: 0,
        cornerRadius: 0,
      },
      {
        type: "text",
        x: 145,
        y: 200,
        width: 1000,
        height: 200,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        name: "Headline",
        text: "Your App Name",
        fontSize: 120,
        fontFamily: "SF Pro Display",
        fontStyle: "normal",
        fontWeight: "bold",
        fill: "#ffffff",
        align: "center",
        lineHeight: 1.2,
      },
      {
        type: "text",
        x: 195,
        y: 420,
        width: 900,
        height: 100,
        rotation: 0,
        opacity: 0.8,
        visible: true,
        locked: false,
        name: "Subtitle",
        text: "A short description of your feature",
        fontSize: 56,
        fontFamily: "SF Pro Display",
        fontStyle: "normal",
        fontWeight: "normal",
        fill: "#ffffff",
        align: "center",
        lineHeight: 1.4,
      },
    ],
  },
  {
    id: "feature-highlight",
    name: "Feature Highlight",
    description: "Highlight a specific feature with text on the side",
    deviceTarget: "iphone-6.7",
    backgroundColor: "#0f0f23",
    elements: [
      {
        type: "rectangle",
        x: 0,
        y: 0,
        width: 1290,
        height: 2796,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        name: "Background",
        fill: "#0f0f23",
        stroke: "",
        strokeWidth: 0,
        cornerRadius: 0,
      },
      {
        type: "text",
        x: 145,
        y: 180,
        width: 1000,
        height: 160,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        name: "Feature Title",
        text: "Smart Notifications",
        fontSize: 96,
        fontFamily: "SF Pro Display",
        fontStyle: "normal",
        fontWeight: "bold",
        fill: "#ffffff",
        align: "center",
        lineHeight: 1.2,
      },
      {
        type: "text",
        x: 195,
        y: 380,
        width: 900,
        height: 120,
        rotation: 0,
        opacity: 0.7,
        visible: true,
        locked: false,
        name: "Feature Description",
        text: "Never miss what matters most to you",
        fontSize: 48,
        fontFamily: "SF Pro Display",
        fontStyle: "normal",
        fontWeight: "normal",
        fill: "#ffffff",
        align: "center",
        lineHeight: 1.4,
      },
      {
        type: "rectangle",
        x: 145,
        y: 600,
        width: 1000,
        height: 1800,
        rotation: 0,
        opacity: 0.1,
        visible: true,
        locked: false,
        name: "Screenshot Placeholder",
        fill: "#ffffff",
        stroke: "#ffffff",
        strokeWidth: 2,
        cornerRadius: 40,
      },
    ],
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Clean minimal layout with centered text",
    deviceTarget: "iphone-6.7",
    backgroundColor: "#ffffff",
    elements: [
      {
        type: "rectangle",
        x: 0,
        y: 0,
        width: 1290,
        height: 2796,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        name: "Background",
        fill: "#ffffff",
        stroke: "",
        strokeWidth: 0,
        cornerRadius: 0,
      },
      {
        type: "text",
        x: 145,
        y: 250,
        width: 1000,
        height: 200,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        name: "Title",
        text: "Simple. Beautiful.",
        fontSize: 108,
        fontFamily: "SF Pro Display",
        fontStyle: "normal",
        fontWeight: "bold",
        fill: "#000000",
        align: "center",
        lineHeight: 1.2,
      },
    ],
  },
  {
    id: "gradient-bold",
    name: "Gradient Bold",
    description: "Bold gradient background with large text",
    deviceTarget: "iphone-6.7",
    backgroundColor: "#667eea",
    elements: [
      {
        type: "rectangle",
        x: 0,
        y: 0,
        width: 1290,
        height: 2796,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        name: "Background",
        fill: "#667eea",
        stroke: "",
        strokeWidth: 0,
        cornerRadius: 0,
      },
      {
        type: "text",
        x: 95,
        y: 300,
        width: 1100,
        height: 300,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        name: "Big Title",
        text: "LEVEL UP",
        fontSize: 160,
        fontFamily: "SF Pro Display",
        fontStyle: "normal",
        fontWeight: "bold",
        fill: "#ffffff",
        align: "center",
        lineHeight: 1.1,
      },
      {
        type: "text",
        x: 195,
        y: 560,
        width: 900,
        height: 100,
        rotation: 0,
        opacity: 0.9,
        visible: true,
        locked: false,
        name: "Tagline",
        text: "Your productivity, reimagined",
        fontSize: 52,
        fontFamily: "SF Pro Display",
        fontStyle: "normal",
        fontWeight: "normal",
        fill: "#ffffff",
        align: "center",
        lineHeight: 1.4,
      },
    ],
  },
];
